apiVersion: apps/v1
kind: Deployment
metadata:
  name: faculty-deply
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      layer: faculty
      app: learn-app
  template:
    metadata:
      name: faculty-pod
      labels:
        layer: faculty
        app: learn-app
    spec:
      containers:
      - name: faculty-cont
        image: 339713063356.dkr.ecr.us-west-1.amazonaws.com/learn-faculty:v1.0.1
        imagePullPolicy: Always
        ports:
        - name: web
          containerPort: 80
          protocol: TCP
        resources:
          requests:
            memory: "200Mi"
            cpu: "2"
          limits:
            memory: "270Mi"
            cpu: "2"
