apiVersion: apps/v1
kind: Deployment
metadata:
  name: subject-deply
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      layer: subject
      app: learn-app
  template:
    metadata:
      name: subject-pod
      labels:
        layer: subject
        app: learn-app
    spec:
      containers:
      - name: subject-cont
        image: 339713063356.dkr.ecr.us-west-1.amazonaws.com/learn-subject:v1.0.2
        ports:
        - name: web
          containerPort: 80
          protocol: TCP
        resources:
          requests:
            memory: "200Mi"
            cpu: "2"
          limits:
            memory: "270Mi"
            cpu: "2"
