name: Frontend containerize and push to ECR.

on:
  push:
    branches: ["main"]
    paths:
      - 'frontend/**'

  workflow_dispatch:

env:
  AWS_REGION: us-west-1
  REPOSITORY: learn-frontend
  REGISTRY: Amazon ECR
 

jobs:
    frontend-build-and-push:
      runs-on: ubuntu-latest
      permissions:
            contents: read
            packages: write

      steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necessary to fetch all tags and history
  
      # Set up Node.js environment
      - name: Set up Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Clear npm cache
        run: npm cache clean --force

      # Install Angular Dependencies
      - name: Install Angular Dependencies
        working-directory: frontend
        run: |
          rm -rf node_modules package-lock.json
          npm install

      # Build Angular Frontend
      - name: Build Angular Frontend
        working-directory: frontend
        run: npm run build --prod
  

      - name: Setup Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
  
  ################################################################
  ###               DETERMINE NEXT VERSION                     ###
  ###   Used for creating new releases and image tags          ###
  ################################################################
  
      - name: Determine Next Version
        id: next_version
        run: |
          # Fetch all tags
          git fetch --tags
          
          # Get the latest tag, assume semver, and sort.
          LATEST_TAG=$(git tag -l | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n1)
          
          # If there's no tag yet, start with v1.0.0.
          if [ -z "$LATEST_TAG" ]; then
            LATEST_TAG="v1.0.0"
          fi
          
          # Increment the patch version
          NEXT_TAG=$(echo $LATEST_TAG | awk -F. '{print $1"."$2"."$3+1}')
          
          # Output the next version
          echo "::set-output name=tag::$NEXT_TAG"
          echo "Next version: $NEXT_TAG"
  
  ################################################################
  ###                     CREATE RELEASE                       ###
  ###  Creating release with the tag from the previous step    ###
  ################################################################
  
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag_name: ${{ steps.next_version.outputs.tag }}
          release_name: learn-frontend ${{ steps.next_version.outputs.tag }}
          draft: false
          prerelease: false
  
  ###########################################################
  #####      Log into repos and build docker image        #####
  ###########################################################
    
      # - name: Extract repository name
      #   id: repo-name
      #   run: |
      #     REPO_NAME="${GITHUB_REPOSITORY##*/}"
      #     echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV
      #     echo "::set-output name=repo_name::$REPO_NAME"
      
  
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
  
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.REPOSITORY }}
          IMAGE_TAG: ${{ steps.next_version.outputs.tag }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f frontend/Dockerfile frontend 
          echo "IMAGE_NAME=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV
  
  ##################################################################
  ###  Snyk & SonarCloud image scans | If fails, drop the action ###
  ##################################################################              
                 
      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
           image: ${{ steps.build-image.outputs.name }}
           args: | 
             --severity-threshold=high --policy-path=.snyk
             --file=frontend/Dockerfile
        continue-on-error: true
      

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=Elsgit1_Els-learning-management-system
            -Dsonar.organization=elsgit1
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.projectBaseDir=frontend
            -Dsonar.sources=frontend/src
            # -Dsonar.tests=frontend/src
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
  ###########################################################
  ###                   PUSH IMAGE TO ECR                 ###
  ###     Tag Docker image as "latest" and push to ECR    ###
  ########################################################### 
  
      - name: Push Docker image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.REPOSITORY }}
          IMAGE_TAG: ${{ steps.next_version.outputs.tag }}
          APP_NAME: learn-frontend
          DOCKERHUB_USERNAME: elsdokr
        run: |
          
          #Tag and push to ECR
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$APP_NAME:$IMAGE_TAG
          docker push $ECR_REGISTRY/$APP_NAME:$IMAGE_TAG

          #Tag and push to DockerHub
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $DOCKERHUB_USERNAME/$APP_NAME:$IMAGE_TAG
          docker push $DOCKERHUB_USERNAME/$APP_NAME:$IMAGE_TAG

  ###########################################################
  ###            Update image name in manifest            ###
  ###########################################################         

      - name: Update Manifest
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.REPOSITORY }}
          IMAGE_TAG: ${{ steps.next_version.outputs.tag }}
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          sed -i 's|image: .*|image: '"$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"'|g' k8s_manifests/frontend-deply.yml
          echo "Updated deployment image with ${{ steps.next_version.outputs.tag }}"

      - name: Commit and push changes
        run: |
          git add k8s_manifests/frontend-deply.yml
          git commit -m "Updated deployment image to ${{ steps.next_version.outputs.tag }}"
          git push origin main
          

