name: Frontend code analysis and security scan.

on:
  pull_request: 
    branches: ["main"]
    paths:
      - 'frontend/**'

  workflow_dispatch:    

jobs:
    code-scans:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
  
      steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necessary to fetch all tags and history

      # - name: Set up JDK
      #   uses: actions/setup-java@v4
      #   with:
      #     distribution: 'temurin'
      #     java-version: '11'

      # - name: Compile Java code
      #   run: |
      #     cd frontend
      #     mvn clean compile
  
  ################################################################
  ###               SONAR CLOUD SCAN                           ###
  ### Drops the build if any bugs or vulnerabilities are found.###
  ###            Using the default quality gate.               ###
  ###        Connected to my personal Sonar Cloud account      ###
  ################################################################
  
      # - name: SonarCloud Scan
      #   uses: SonarSource/sonarcloud-github-action@master
      #   with:
      #     args: >
      #       -Dsonar.projectKey=Elsgit1_Els-learning-management-system
      #       -Dsonar.organization=elsgit1
      #       -Dsonar.host.url=https://sonarcloud.io
      #       -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      #       -Dsonar.java.binaries=frontend/target/classes
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
      - name: Setup Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

  ###########################################################
  ###  Docker image Snyk scan | If fails, drop the action ###
  ###       Connected to my personal Snyk account         ###
  ###     The code owner receives an email notification   ###
  ### Possible to configure Slack notification if needed  ###
  ###########################################################               
                 
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
        #    image: ${{ env.IMAGE_NAME }}
           args: --severity-threshold=high --policy-path=.snyk
        continue-on-error: true